# Generated by Django 6.0.5 on 2026-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='financials_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
